safe:        false
port: 4000
baseurl:    /
url: http://latentflip.com

source:      .
destination: ./_site

future:      true
lsi:         false
highlighter: rouge
permalink:   ":title"

maruku:
  use_tex:    false
  use_divs:   true
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

exclude: ['node_modules']
  
kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

name: Philip Roberts
description: Musings and essays by Philip Roberts
url: http://latentflip.com
